version: 2

models:
  
  - name: dim_users
    description: A view that stores each user with associated address and user metadata. Each user could potentially have many addresses, so all address data is stored as an aggregated comma-separated list string. Please note that indices match (i.e., associated address id index 1 == associated country index 1)
    columns:
      - name: user_id
        tests: 
          - not_null
          - unique
      - name: first_name
      - name: last_name 
      - name: user_first_name_last_name
      - name: email 
      - name: phone_number 
      - name: user_created_at_utc 
      - name: user_associated_address_ids_commasep
      - name: user_associated_addresses_commasep
      - name: user_associated_zipcodes_commasep
      - name: user_associated_states_commasep
      - name: user_associated_countries_commasep
      - name: unique_associated_address_ids
      - name: unique_associated_addresses 
      - name: unique_associated_zipcodes
      - name: unique_associated_states
      - name: unique_associated_countries
 
     

