version: 2

models:
  
  - name: int_active_promos
    description: A view that stores only active promotions. This ensures we do not mistakenly apply inactive promos.
    columns:
      - name: active_promo_id
        tests: 
          - not_null
          - unique
      - name: active_price_discount_in_usd
        tests: 
          - not_null
          - positive_values 

  - name: int_order_products
    description: A view that stores each unique order_id with associated product information. All product names and costs are stored as comma separated strings. Index of value in comma separated list matches (meaning product name index 1 == product price index 1).
    columns:
      - name: order_id
        tests: 
          - not_null
          - unique
      - name: product_names_in_order_commasep
      - name: total_product_in_order_commasep
      - name: total_order_products
        tests: 
          - positive_values
  
  - name: int_user_orders
    description: A table storing all order-related pageviews at user-level. Each row is unique at event<>user level. Data is joined to most recent order details. 
    tests: 
      - unique:
            column_name: "order_id || '-' || user_id"
    columns:
      - name: order_id 
        tests: 
          - not_null
      - name: active_promo_id 
      - name: user_id
        tests: 
          - not_null
      - name: user_first_name_last_name
      - name: email
      - name: phone_number 
      - name: user_created_at_utc
      - name: days_since_user_created
        tests: 
          - positive_values
      - name: order_address_id
      - name: order_address
      - name: order_zipcode
      - name: order_state
      - name: order_country
      - name: order_created_at_utc
      - name: product_names_in_order_commasep
      - name: total_products_in_order_commasep
      - name: total_order_items
      - name: total_order_products
      - name: order_cost_usd
      - name: active_price_discount_in_usd
      - name: shipping_cost_usd
      - name: order_total_usd
      - name: average_total_cost_per_item_usd
      - name: tracking_id 
      - name: shipping_service 
      - name: estimated_delivery_at_utc
      - name: delivered_at_utc
      - name: days_to_deliver
      - name: days_to_estimated_delivered_minus_delivered
      - name: estimated_delivery_performance
      - name: is_delivered

